version: '3.9'
services:
  face_recognition:
    build: .
    volumes:
      - .:/app
    devices:
      - "/dev/video0:/dev/video0"  # 🎥 Access webcam on host
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
